apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: faithful-starfish-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-hub/faithful-starfish-java-quarkus-gitops